import type { GovernanceControl, ControlMappingEntry } from "@nexus/shared-types";

const F = (frameworkId: string, refs: string[]) => ({ frameworkId, refs });

export const GOVERNANCE_CONTROLS: GovernanceControl[] = [
  {
    id: "MFA-PRIV-001",
    name: "Multi-Factor Authentication for Privileged Access",
    category: "Access Control",
    coreRequirement: "Require MFA for all privileged and remote administrative access.",
    severity: "CRITICAL",
    description: "Privileged accounts must never rely on a single factor. Enforce MFA on admin portals, identity providers and remote access.",
    mappedTo: [
      F("iso-27001", ["A.5.15", "A.8.2", "A.8.5"]),
      F("nist-csf", ["PR.AC-01", "PR.AC-07", "DE.AE-02"]),
      F("nist-sp800-53", ["IA-2", "IA-5", "AC-3"]),
      F("cis", ["6.4", "6.6", "1.2"]),
      F("nis2", ["Art.21 access control", "Art.21(2)(g) authentication"]),
      F("dora", ["Art.9 ICT risk management"]),
      F("gdpr", ["Art.32 security of processing"]),
      F("certin", ["3.2", "3.5"]),
      F("dpdp", ["S.8 reasonable safeguards"]),
      F("stig", ["Authentication policy", "CAT I"]),
      F("fedramp", ["AC-2", "IA-2", "IA-5"]),
      F("cisaguidance", ["Zero Trust Maturity – Identity"]),
      F("nist80053", ["IA-2(1)", "IA-2(2)"]),
      F("nciplc", ["Access control protection"]),
      F("nist800171", ["3.5.3"]),
    ],
  },
  {
    id: "AUTH-001",
    name: "Strong Authentication",
    category: "Access Control",
    coreRequirement: "Enforce strong credential policies and modern authentication protocols.",
    severity: "HIGH",
    description: "Avoid legacy or weak authentication. Use strong password policy, key-based authentication and modern protocols.",
    mappedTo: [
      F("iso-27001", ["A.5.17", "A.8.2"]),
      F("nist-csf", ["PR.AC-01", "PR.AC-07"]),
      F("nist-sp800-53", ["IA-5", "IA-8"]),
      F("cis", ["5.2", "6.1", "6.4"]),
      F("nis2", ["Art.21 risk mitigation"]),
      F("dora", ["Art.9 ICT operations"]),
      F("stig", ["Authentication policy"]),
      F("certin", ["3.5"]),
      F("nist80053", ["IA-5"]),
    ],
  },
  {
    id: "ACCESS-001",
    name: "Least Privilege and Access Control",
    category: "Access Control",
    coreRequirement: "Restrict data and system access to the minimum required for each role.",
    severity: "HIGH",
    description: "Implement role-based access control, separation of duties and regular access reviews.",
    mappedTo: [
      F("iso-27001", ["A.5.18", "A.8.2", "A.5.3"]),
      F("nist-csf", ["PR.AC-04", "PR.AC-06"]),
      F("nist-sp800-53", ["AC-1", "AC-2", "AC-6"]),
      F("cis", ["5.1", "5.2", "6.8"]),
      F("nis2", ["Art.21 access control"]),
      F("dora", ["Art.9 access management"]),
      F("gdpr", ["Art.32", "Art.25"]),
      F("certin", ["3.2", "3.5"]),
      F("dpdp", ["S.8"]),
      F("stig", ["Access control"]),
      F("fedramp", ["AC-2", "AC-6"]),
      F("nist80053", ["AC-6", "AC-2"]),
      F("nist800171", ["3.1.1", "3.1.2", "3.1.5"]),
    ],
  },
  {
    id: "SEG-001",
    name: "Network Segmentation",
    category: "Network Security",
    coreRequirement: "Segment networks to isolate critical systems from lower-trust zones.",
    severity: "HIGH",
    description: "Use segmentation, zone-based policies and micro-segmentation to contain lateral movement.",
    mappedTo: [
      F("iso-27001", ["A.8.22", "A.8.20"]),
      F("nist-csf", ["PR.PT-04", "PR.AC-05"]),
      F("nist-sp800-53", ["SC-7", "AC-4"]),
      F("cis", ["14.1", "14.6", "4.4"]),
      F("nis2", ["Art.21 network security"]),
      F("dora", ["Art.9 ICT protection"]),
      F("certin", ["3.3"]),
      F("stig", ["Network boundary"]),
      F("fedramp", ["SC-7", "AC-4"]),
      F("nist80053", ["SC-7"]),
      F("nciplc", ["Boundary protection"]),
      F("nist800171", ["3.13.1", "3.13.5"]),
    ],
  },
  {
    id: "DDENY-001",
    name: "Default Deny / Zero Trust Traffic Enforcement",
    category: "Network Security",
    coreRequirement: "Deny all traffic not explicitly permitted.",
    severity: "HIGH",
    description: "Traffic should be denied by default. Only explicitly allowed flows should traverse the boundary.",
    mappedTo: [
      F("iso-27001", ["A.8.20", "A.5.15"]),
      F("nist-csf", ["PR.PT-04", "PR.AC-05"]),
      F("nist-sp800-53", ["AC-4", "CM-6"]),
      F("cis", ["4.4", "4.2"]),
      F("nis2", ["Art.21"]),
      F("dora", ["Art.9"]),
      F("certin", ["3.3"]),
      F("stig", ["Default deny"]),
      F("nist80053", ["AC-4"]),
      F("nist800171", ["3.13.1"]),
    ],
  },
  {
    id: "PROTO-001",
    name: "Insecure Protocols Disabled",
    category: "Network Security",
    coreRequirement: "Disable plaintext protocols such as Telnet, FTP and TFTP.",
    severity: "CRITICAL",
    description: "Plaintext protocols expose credentials and data on the wire. Disable them and enforce encrypted equivalents.",
    mappedTo: [
      F("iso-27001", ["A.8.25", "A.8.26"]),
      F("nist-csf", ["PR.DS-02", "DE.CM-04"]),
      F("nist-sp800-53", ["SC-8", "CM-6"]),
      F("cis", ["3.3", "3.4", "16.7"]),
      F("nis2", ["Art.21 encryption"]),
      F("dora", ["Art.9 security"]),
      F("certin", ["3.4"]),
      F("stig", ["CAT I – insecure protocols"]),
      F("fedramp", ["SC-8", "SC-13"]),
      F("nist80053", ["SC-8"]),
      F("nciplc", ["Secure protocol use"]),
      F("nist800171", ["3.13.8", "3.13.2"]),
      F("cis-benchmarks", ["1.4.1 Disabled insecure protocols", "4.2 Enable encrypted remote access"]),
    ],
  },
  {
    id: "MGMT-001",
    name: "Secure Management Interfaces",
    category: "Network Security",
    coreRequirement: "Expose management interfaces only over encrypted channels and restrict access.",
    severity: "HIGH",
    description: "Management interfaces (SSH, HTTPS) must be encrypted, version-restricted and access-controlled.",
    mappedTo: [
      F("iso-27001", ["A.8.20", "A.8.23"]),
      F("nist-csf", ["PR.AC-03", "PR.DS-02"]),
      F("nist-sp800-53", ["AC-3", "SC-8", "IA-2"]),
      F("cis", ["3.3", "3.4", "16.7"]),
      F("nis2", ["Art.21"]),
      F("dora", ["Art.9"]),
      F("certin", ["3.4", "3.5"]),
      F("stig", ["Management interface hardening"]),
      F("nist80053", ["SC-8", "AC-3"]),
      F("nist800171", ["3.13.2"]),
      F("cis-benchmarks", ["2.1.1 Verify management network restrictions"]),
    ],
  },
  {
    id: "ADMIN-001",
    name: "Restricted Administrative Exposure",
    category: "Access Control",
    coreRequirement: "Administrative access must be source-restricted and never exposed openly.",
    severity: "CRITICAL",
    description: "Admin interfaces must be reachable only from dedicated, source-restricted management networks.",
    mappedTo: [
      F("iso-27001", ["A.8.2", "A.5.15"]),
      F("nist-csf", ["PR.AC-04", "PR.AC-07"]),
      F("nist-sp800-53", ["AC-3", "AC-6", "SC-7"]),
      F("cis", ["5.4", "14.2", "6.6"]),
      F("nis2", ["Art.21 access control"]),
      F("dora", ["Art.9 access management"]),
      F("certin", ["3.2"]),
      F("stig", ["Boundary protection"]),
      F("nist80053", ["SC-7", "AC-6"]),
      F("nist800171", ["3.1.1", "3.1.2"]),
      F("cis-benchmarks", ["5.1.1 Restrict admin access to source networks", "5.2.1 Set default deny on management interfaces"]),
    ],
  },
  {
    id: "LOG-001",
    name: "Centralized Logging and Monitoring",
    category: "Detection & Response",
    coreRequirement: "Collect, centralize and retain security-relevant logs with integrity protection.",
    severity: "MEDIUM",
    description: "Enable audit logging across systems, stream to a central SIEM, protect logs from tampering, and alert on anomalies.",
    mappedTo: [
      F("iso-27001", ["A.8.15", "A.8.16"]),
      F("nist-csf", ["DE.CM-01", "PR.PT-01"]),
      F("nist-sp800-53", ["AU-2", "AU-6", "AU-12"]),
      F("cis", ["8.1", "8.2", "8.5", "13.1"]),
      F("nis2", ["Art.21 monitoring", "Art.23 incident handling"]),
      F("dora", ["Art.10 incident reporting"]),
      F("gdpr", ["Art.32", "Art.33 breach log"]),
      F("certin", ["3.5", "6"]),
      F("dpdp", ["S.8 safeguards"]),
      F("stig", ["Audit policy"]),
      F("fedramp", ["AU-2", "AU-6"]),
      F("nist80053", ["AU-2", "AU-12"]),
      F("nist800171", ["3.3.1", "3.3.2", "3.3.3", "3.11.2"]),
      F("cis-benchmarks", ["8.1.1 Enable centralized logging", "8.2.1 Configure SIEM integration"]),
    ],
  },
  {
    id: "CRYPT-001",
    name: "Encryption in Transit and at Rest",
    category: "Data Protection",
    coreRequirement: "Encrypt sensitive data in transit and at rest using approved algorithms.",
    severity: "HIGH",
    description: "Enforce TLS for transit and strong key management for data at rest across all storage tiers.",
    mappedTo: [
      F("iso-27001", ["A.8.24", "A.8.25"]),
      F("nist-csf", ["PR.DS-01", "PR.DS-02"]),
      F("nist-sp800-53", ["SC-8", "SC-13", "SC-28"]),
      F("cis", ["3.3", "3.7", "3.8"]),
      F("nis2", ["Art.21(2)(h) encryption"]),
      F("dora", ["Art.9"]),
      F("gdpr", ["Art.32"]),
      F("certin", ["3.4"]),
      F("dpdp", ["S.8"]),
      F("stig", ["Encryption standard"]),
      F("fedramp", ["SC-8", "SC-13", "SC-28"]),
      F("nist80053", ["SC-8", "SC-13", "SC-28"]),
      F("nciplc", ["Data protection"]),
      F("nist800171", ["3.13.8", "3.13.16"]),
      F("cis-benchmarks", ["3.1.1 Enforce TLS 1.2+", "3.2.1 Enforce encryption at rest"]),
    ],
  },
  {
    id: "DATA-001",
    name: "Data Retention, Residency and Minimization",
    category: "Data Protection",
    coreRequirement: "Define and enforce retention limits and residency requirements per jurisdiction.",
    severity: "MEDIUM",
    description: "Retain data only as long as required, keep it within permitted jurisdictions, and minimize collection.",
    mappedTo: [
      F("iso-27001", ["A.5.10", "A.5.33"]),
      F("nist-csf", ["PR.DS-04", "PR.DS-05"]),
      F("nist-sp800-53", ["SI-12", "AU-11", "SC-28"]),
      F("cis", ["3.9", "8.5"]),
      F("gdpr", ["Art.5", "Art.30", "Art.32"]),
      F("dpdp", ["S.5", "S.9", "S.11"]),
      F("nis2", ["Art.21"]),
      F("dora", ["Art.9"]),
      F("certin", ["3.4", "6"]),
      F("nist80053", ["SI-12"]),
    ],
  },
  {
    id: "IR-001",
    name: "Incident Response and Notification",
    category: "Detection & Response",
    coreRequirement: "Detect, contain and report security incidents with defined timelines.",
    severity: "HIGH",
    description: "Maintain an incident response plan, escalation paths, and mandatory notification timelines per jurisdiction.",
    mappedTo: [
      F("iso-27001", ["A.5.24", "A.5.25", "A.5.26", "A.5.27"]),
      F("nist-csf", ["RS.RP-01", "RS.CO-04", "IR-1"]),
      F("nist-sp800-53", ["IR-4", "IR-6", "IR-8"]),
      F("cis", ["17.1", "17.2", "18.1"]),
      F("nis2", ["Art.23 incident handling", "Art.20 notification"]),
      F("dora", ["Art.10", "Art.11", "Art.17"]),
      F("gdpr", ["Art.33", "Art.34"]),
      F("certin", ["6 security incidents"]),
      F("dpdp", ["S.8"]),
      F("stig", ["Incident response"]),
      F("fedramp", ["IR-4", "IR-6"]),
      F("nist80053", ["IR-4", "IR-6"]),
      F("nist800171", ["3.6.1", "3.6.2", "3.6.3"]),
    ],
  },
  {
    id: "ASSET-001",
    name: "Asset Inventory and Classification",
    category: "Asset Management",
    coreRequirement: "Maintain an accurate inventory of systems, data and internal assets.",
    severity: "MEDIUM",
    description: "Identify, classify and track every asset supporting regulated processes and data.",
    mappedTo: [
      F("iso-27001", ["A.5.9", "A.5.10"]),
      F("nist-csf", ["ID.AM-01", "ID.AM-02", "ID.AM-05"]),
      F("nist-sp800-53", ["CM-8", "RA-3", "PL-2"]),
      F("cis", ["1.1", "1.4", "2.1"]),
      F("nis2", ["Art.21 asset management"]),
      F("dora", ["Art.9"]),
      F("certin", ["3.1"]),
      F("nist80053", ["CM-8"]),
      F("nist800171", ["3.1.1", "3.1.2"]),
    ],
  },
  {
    id: "PATCH-001",
    name: "Vulnerability and Patch Management",
    category: "System Security",
    coreRequirement: "Assess, prioritize and remediate vulnerabilities within defined timelines.",
    severity: "HIGH",
    description: "Scan for vulnerabilities continuously, prioritize by exploitability and remediate critical findings fast.",
    mappedTo: [
      F("iso-27001", ["A.8.8", "A.5.34"]),
      F("nist-csf", ["ID.RA-01", "PR.IP-12", "DE.CM-08"]),
      F("nist-sp800-53", ["RA-5", "SI-2", "CM-6"]),
      F("cis", ["7.1", "7.4", "7.6"]),
      F("nis2", ["Art.21 vulnerability handling"]),
      F("dora", ["Art.9"]),
      F("certin", ["3.4"]),
      F("stig", ["Patch management"]),
      F("fedramp", ["RA-5", "SI-2"]),
      F("nist80053", ["RA-5", "SI-2"]),
      F("nist800171", ["3.11.2", "3.11.3"]),
      F("cis-benchmarks", ["7.1.1 Enable automated patching", "7.2.1 Configure vulnerability scanning"]),
    ],
  },
  {
    id: "BACKUP-001",
    name: "Backup and Recovery",
    category: "Resilience",
    coreRequirement: "Back up critical data and validate restore capability regularly.",
    severity: "MEDIUM",
    description: "Data and system configuration must be recoverable within resilience objectives.",
    mappedTo: [
      F("iso-27001", ["A.8.13"]),
      F("nist-csf", ["PR.DS-04", "RC.RP-01"]),
      F("nist-sp800-53", ["CP-6", "CP-9", "CP-10"]),
      F("cis", ["11.1", "11.2", "11.3"]),
      F("nis2", ["Art.21 business continuity"]),
      F("dora", ["Art.9 recovery"]),
      F("certin", ["4"]),
      F("nist80053", ["CP-9"]),
      F("nist800171", ["3.13.1", "3.13.8"]),
      F("cis-benchmarks", ["11.1.1 Enable automated backups", "11.2.1 Validate backup restoration"]),
    ],
  },
  {
    id: "VENDOR-001",
    name: "Supply Chain and Vendor Risk",
    category: "Third-Party",
    coreRequirement: "Assess and continuously monitor vendor and sub-vendor security posture.",
    severity: "HIGH",
    description: "Right-party risk extends to sub-vendors. Monitor vendor controls, incidents and concentration risks.",
    mappedTo: [
      F("iso-27001", ["A.5.19", "A.5.20", "A.5.21"]),
      F("nist-csf", ["ID.SC-01", "ID.SC-02", "SA-9"]),
      F("nist-sp800-53", ["SA-9", "SA-12", "CM-9"]),
      F("cis", ["15.1", "15.2", "15.3"]),
      F("nis2", ["Art.21(2)(d) supply chain"]),
      F("dora", ["Art.29", "Art.30", "Art.31"]),
      F("certin", ["3.1"]),
      F("stig", ["Supply chain risk"]),
      F("fedramp", ["SA-9", "SA-12"]),
      F("nist80053", ["SA-9", "SA-12"]),
      F("nist800171", ["3.1.1", "3.1.2"]),
    ],
  },
  {
    id: "CLOUD-001",
    name: "Cloud Configuration Baseline",
    category: "Cloud Security",
    coreRequirement: "Enforce secure-by-default configuration across cloud resources.",
    severity: "HIGH",
    description: "Scan cloud accounts for misconfiguration, exposed storage, excessive permissions and drift from baseline.",
    mappedTo: [
      F("iso-27001", ["A.5.23", "A.8.22"]),
      F("nist-csf", ["PR.AC-05", "PR.PT-03"]),
      F("nist-sp800-53", ["CM-6", "SC-28", "SI-4"]),
      F("cis", ["16.1", "16.11", "3.8"]),
      F("nis2", ["Art.21 cloud security"]),
      F("dora", ["Art.9"]),
      F("certin", ["3.3"]),
      F("fedramp", ["CM-6", "SC-28"]),
      F("nist80053", ["CM-6"]),
      F("nist800171", ["3.13.1", "3.13.2"]),
      F("cis-benchmarks", ["14.1.1 Enable cloud security scanning", "14.2.1 Enforce cloud baseline config"]),
    ],
  },
  {
    id: "AUDIT-001",
    name: "Audit Log Integrity and Immutability",
    category: "Assurance",
    coreRequirement: "Protect security and compliance audit logs from alteration or deletion.",
    severity: "HIGH",
    description: "Audit trails for security decisions must be tamper-evident and cover AI, human and system actions.",
    mappedTo: [
      F("iso-27001", ["A.8.15", "A.8.16"]),
      F("nist-csf", ["PR.PT-01", "DE.CM-01"]),
      F("nist-sp800-53", ["AU-3", "AU-4", "AU-11"]),
      F("cis", ["8.5", "8.10"]),
      F("nis2", ["Art.21 audit"]),
      F("dora", ["Art.9"]),
      F("gdpr", ["Art.5(2)", "Art.30"]),
      F("certin", ["3.5", "10.1"]),
      F("stig", ["Audit log integrity"]),
      F("fedramp", ["AU-3", "AU-11"]),
      F("nist80053", ["AU-3", "AU-11"]),
      F("nist800171", ["3.3.1", "3.3.2", "3.12.1"]),
    ],
  },
  {
    id: "SDLC-001",
    name: "Secure Development Lifecycle",
    category: "Assurance",
    coreRequirement: "Integrate security requirements, review and testing into the development process.",
    severity: "MEDIUM",
    description: "Threat modeling, secure coding standards, and security gates must be part of delivering software.",
    mappedTo: [
      F("iso-27001", ["A.8.25", "A.8.28", "A.8.29"]),
      F("nist-csf", ["PR.DS-06", "DE.CM-08"]),
      F("nist-sp800-53", ["SA-3", "SA-8", "SA-11"]),
      F("cis", ["16.8", "16.9"]),
      F("nis2", ["Art.21"]),
      F("certin", ["3.2"]),
      F("fedramp", ["SA-8", "SA-11"]),
      F("nist80053", ["SA-11"]),
      F("cis-benchmarks", ["16.1.1 Enable SAST gate", "16.2.1 Enforce secure coding standard"]),
    ],
  },
  {
    id: "EMG-001",
    name: "Emergency and Change Controls",
    category: "Change Governance",
    coreRequirement: "All production changes—including emergency—must pass governance and be audited.",
    severity: "HIGH",
    description: "Change freeze, emergency overrides, rollback and post-change verification must be auditable.",
    mappedTo: [
      F("iso-27001", ["A.5.1", "A.8.31", "A.8.32"]),
      F("nist-csf", ["PR.IP-03", "RC.RP-01"]),
      F("nist-sp800-53", ["CM-3", "CM-4", "CM-5"]),
      F("cis", ["4.4", "17.1"]),
      F("nis2", ["Art.21 change management"]),
      F("dora", ["Art.9 change management"]),
      F("certin", ["10.1 change management"]),
      F("nist80053", ["CM-3", "CM-4", "CM-5"]),
      F("nist800171", ["3.13.1", "3.13.2"]),
    ],
  },
];

export const GOVERNANCE_CONTROL_INDEX = new Map<string, GovernanceControl>(GOVERNANCE_CONTROLS.map((c) => [c.id, c]));

export function controlMappings(): ControlMappingEntry[] {
  return GOVERNANCE_CONTROLS.map((c) => ({
    controlId: c.id,
    controlName: c.name,
    category: c.category,
    coreRequirement: c.coreRequirement,
    frameworks: c.mappedTo.map((m) => ({ id: m.frameworkId, code: m.frameworkId.toUpperCase(), refs: m.refs })),
  }));
}