import type { ComplianceFrameworkDef } from "@nexus/shared-types";

const CONTROL = (id: string) => id;

export const FRAMEWORKS: ComplianceFrameworkDef[] = [
  {
    id: "iso-27001",
    code: "ISO/IEC 27001",
    name: "ISO/IEC 27001 Information Security Management",
    region: "GLOBAL",
    bloc: "GLOBAL",
    authority: "ISO / IEC",
    status: "active",
    version: "2022",
    description: "International standard for an information security management system (ISMS).",
    intent: "Certify a systematic, risk-based information security management approach.",
    whyApplies: "ISO 27001 is the de-facto baseline for information security governance and is widely accepted across all regions and industries.",
    triggers: [{ field: "criticality", operator: "always", value: [] }],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("AUTH-001"),
      CONTROL("ACCESS-001"),
      CONTROL("SEG-001"),
      CONTROL("DDENY-001"),
      CONTROL("PROTO-001"),
      CONTROL("MGMT-001"),
      CONTROL("ADMIN-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("DATA-001"),
      CONTROL("IR-001"),
      CONTROL("ASSET-001"),
      CONTROL("PATCH-001"),
      CONTROL("BACKUP-001"),
      CONTROL("VENDOR-001"),
      CONTROL("CLOUD-001"),
      CONTROL("AUDIT-001"),
      CONTROL("SDLC-001"),
      CONTROL("EMG-001"),
    ],
    baselineScore: 93,
    baselineControls: { passed: 18, total: 20 },
  },
  {
    id: "nist-csf",
    code: "NIST CSF",
    name: "NIST Cybersecurity Framework",
    region: "GLOBAL",
    bloc: "GLOBAL",
    authority: "U.S. NIST",
    status: "active",
    version: "2.0",
    description: "Framework of voluntary cybersecurity outcomes organized into Govern, Identify, Protect, Detect, Respond and Recover.",
    intent: "Align security program outcomes with recognized best practice in a business-risk language.",
    whyApplies: "Recommended baseline for organizations operating with U.S. links and broadly used as a neutral security framework internationally.",
    triggers: [{ field: "criticality", operator: "always", value: [] }],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("AUTH-001"),
      CONTROL("ACCESS-001"),
      CONTROL("SEG-001"),
      CONTROL("DDENY-001"),
      CONTROL("PROTO-001"),
      CONTROL("MGMT-001"),
      CONTROL("ADMIN-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("IR-001"),
      CONTROL("ASSET-001"),
      CONTROL("PATCH-001"),
      CONTROL("BACKUP-001"),
      CONTROL("VENDOR-001"),
      CONTROL("AUDIT-001"),
    ],
    baselineScore: 91,
    baselineControls: { passed: 15, total: 16 },
  },
  {
    id: "nist-sp800-53",
    code: "NIST SP 800-53",
    name: "NIST SP 800-53 Security & Privacy Controls",
    region: "US",
    bloc: "US",
    authority: "U.S. NIST",
    status: "active",
    version: "r5",
    description: "Comprehensive control catalog used for federal systems and FedRAMP authorizations.",
    intent: "Meet federal security control baselines for systems processing federal information.",
    whyApplies: "Selected because the organization reports U.S. operating regions or supplies to the U.S. public sector.",
    triggers: [
      { field: "regions", operator: "in", value: ["US"] },
      { field: "businessSectors", operator: "any", value: ["GOVERNMENT", "DEFENSE", "PUBLIC_SECTOR", "CRITICAL_INFRA"] },
    ],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("AUTH-001"),
      CONTROL("ACCESS-001"),
      CONTROL("SEG-001"),
      CONTROL("DDENY-001"),
      CONTROL("PROTO-001"),
      CONTROL("MGMT-001"),
      CONTROL("ADMIN-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("IR-001"),
      CONTROL("ASSET-001"),
      CONTROL("PATCH-001"),
      CONTROL("BACKUP-001"),
      CONTROL("VENDOR-001"),
      CONTROL("CLOUD-001"),
      CONTROL("AUDIT-001"),
      CONTROL("SDLC-001"),
      CONTROL("EMG-001"),
    ],
    baselineScore: 87,
    baselineControls: { passed: 16, total: 19 },
  },
  {
    id: "cis",
    code: "CIS Controls",
    name: "CIS Critical Security Controls v8",
    region: "GLOBAL",
    bloc: "GLOBAL",
    authority: "Center for Internet Security",
    status: "active",
    version: "v8",
    description: "Prioritized set of safeguards to mitigate the most common cyber attacks.",
    intent: "Establish prioritized, actionable safeguards aligned to real threat prevention.",
    whyApplies: "Applied as the technical hardening baseline for all covered systems.",
    triggers: [{ field: "criticality", operator: "always", value: [] }],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("AUTH-001"),
      CONTROL("ACCESS-001"),
      CONTROL("SEG-001"),
      CONTROL("DDENY-001"),
      CONTROL("PROTO-001"),
      CONTROL("MGMT-001"),
      CONTROL("ADMIN-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("IR-001"),
      CONTROL("ASSET-001"),
      CONTROL("PATCH-001"),
      CONTROL("BACKUP-001"),
      CONTROL("VENDOR-001"),
      CONTROL("CLOUD-001"),
      CONTROL("SDLC-001"),
    ],
    baselineScore: 89,
    baselineControls: { passed: 15, total: 17 },
  },
  {
    id: "cis-benchmarks",
    code: "CIS Benchmarks",
    name: "CIS Benchmarks — Technical Hardening Baselines",
    region: "GLOBAL",
    bloc: "GLOBAL",
    authority: "Center for Internet Security",
    status: "active",
    version: "v1.1+",
    description: "Prescriptive configuration baselines for operating systems, cloud platforms and applications, aligned with CIS Controls.",
    intent: "Provide vendor-specific hardening baselines that operationalize the CIS Controls safeguards.",
    whyApplies: "Applied as the default technical configuration baseline across servers, endpoints and cloud workloads.",
    triggers: [{ field: "criticality", operator: "always", value: [] }],
    controlIds: [
      CONTROL("PROTO-001"),
      CONTROL("MGMT-001"),
      CONTROL("ADMIN-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("PATCH-001"),
      CONTROL("CLOUD-001"),
      CONTROL("BACKUP-001"),
      CONTROL("SDLC-001"),
    ],
    baselineScore: 90,
    baselineControls: { passed: 8, total: 9 },
  },
  {
    id: "nist-sp800-171",
    code: "NIST 800-171",
    name: "NIST SP 800-171 Protecting CUI",
    region: "US",
    bloc: "US",
    authority: "U.S. NIST",
    status: "active",
    version: "r2",
    description: "Safeguards for Controlled Unclassified Information (CUI) in non-federal systems.",
    intent: "Protect CUI processed or stored by contractors and non-federal organizations.",
    whyApplies: "Applies where the organization is a government contractor handling CUI under DFARS 7012.",
    triggers: [
      { field: "businessSectors", operator: "any", value: ["DEFENSE", "GOVERNMENT", "PUBLIC_SECTOR"] },
      { field: "dataTypes", operator: "any", value: ["CLASSIFIED", "INTERNAL"] },
    ],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("ACCESS-001"),
      CONTROL("SEG-001"),
      CONTROL("DDENY-001"),
      CONTROL("PROTO-001"),
      CONTROL("MGMT-001"),
      CONTROL("ADMIN-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("IR-001"),
      CONTROL("ASSET-001"),
      CONTROL("PATCH-001"),
      CONTROL("BACKUP-001"),
      CONTROL("VENDOR-001"),
      CONTROL("AUDIT-001"),
    ],
    baselineScore: 82,
    baselineControls: { passed: 12, total: 15 },
  },
  {
    id: "fedramp",
    code: "FedRAMP",
    name: "FedRAMP",
    region: "US",
    bloc: "US",
    authority: "U.S. FedRAMP PMO / GSA",
    status: "active",
    version: "Rev 5",
    description: "Standardized approach to security assessment and authorization for cloud services used by the U.S. federal government.",
    intent: "Authorize cloud offerings against a NIST SP 800-53 baseline with continuous monitoring.",
    whyApplies: "Applies when offering cloud services to U.S. federal buyers.",
    triggers: [
      { field: "regions", operator: "in", value: ["US"] },
      { field: "industries", operator: "any", value: ["cloud-provider", "software-saas"] },
    ],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("AUTH-001"),
      CONTROL("ACCESS-001"),
      CONTROL("SEG-001"),
      CONTROL("PROTO-001"),
      CONTROL("MGMT-001"),
      CONTROL("ADMIN-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("IR-001"),
      CONTROL("ASSET-001"),
      CONTROL("PATCH-001"),
      CONTROL("BACKUP-001"),
      CONTROL("CLOUD-001"),
      CONTROL("AUDIT-001"),
      CONTROL("SDLC-001"),
    ],
    baselineScore: 84,
    baselineControls: { passed: 14, total: 16 },
  },
  {
    id: "cisaguidance",
    code: "CISA Guidance",
    name: "CISA Cybersecurity Guidance & Zero Trust",
    region: "US",
    bloc: "US",
    authority: "U.S. CISA",
    status: "active",
    version: "ZTA Maturity",
    description: "Operational advisories and Zero Trust maturity guidance for critical infrastructure sectors.",
    intent: "Align with CISA Zero Trust Maturity Model and operational warnings.",
    whyApplies: "Selected for U.S.-operating critical infrastructure and technology providers receiving CISA advisories.",
    triggers: [
      { field: "regions", operator: "in", value: ["US"] },
      { field: "industries", operator: "any", value: ["critical-infrastructure", "telecommunications", "energy", "finance", "healthcare", "technology"] },
    ],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("AUTH-001"),
      CONTROL("ACCESS-001"),
      CONTROL("SEG-001"),
      CONTROL("DDENY-001"),
      CONTROL("LOG-001"),
      CONTROL("IR-001"),
      CONTROL("PATCH-001"),
    ],
    baselineScore: 88,
    baselineControls: { passed: 7, total: 8 },
  },
  {
    id: "stig",
    code: "DISA STIG",
    name: "DISA STIG Security Technical Implementation Guides",
    region: "US",
    bloc: "US",
    authority: "U.S. DISA",
    status: "active",
    version: "V1R1+",
    description: "U.S. DoD configuration baselines for networks, platforms and applications.",
    intent: "Apply defense-grade hardening baselines for DoD and defense-supply systems.",
    whyApplies: "Applies where defense or government systems must be configured to DoD STIG baselines.",
    triggers: [
      { field: "industries", operator: "any", value: ["defense", "defense-contractor", "government", "critical-infrastructure"] },
    ],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("AUTH-001"),
      CONTROL("ACCESS-001"),
      CONTROL("SEG-001"),
      CONTROL("DDENY-001"),
      CONTROL("PROTO-001"),
      CONTROL("MGMT-001"),
      CONTROL("ADMIN-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("IR-001"),
      CONTROL("PATCH-001"),
      CONTROL("VENDOR-001"),
      CONTROL("AUDIT-001"),
    ],
    baselineScore: 86,
    baselineControls: { passed: 12, total: 14 },
  },
  {
    id: "nis2",
    code: "NIS2",
    name: "EU NIS2 Directive",
    region: "DE",
    bloc: "EU",
    authority: "European Commission / national CSIRT",
    status: "active",
    version: "EU 2022/2555",
    description: "EU-wide directive on measures for a high common level of cybersecurity across essential and important entities.",
    intent: "Meet cyber risk-management and incident-notification obligations for EU operators.",
    whyApplies: "Applies because the organization operates in the EU and provides essential/important services, or handles EU data subjects.",
    triggers: [
      { field: "regions", operator: "in", value: ["EU"] },
      { field: "customerRegions", operator: "any", value: ["EU"] },
    ],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("AUTH-001"),
      CONTROL("ACCESS-001"),
      CONTROL("SEG-001"),
      CONTROL("DDENY-001"),
      CONTROL("PROTO-001"),
      CONTROL("MGMT-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("IR-001"),
      CONTROL("ASSET-001"),
      CONTROL("PATCH-001"),
      CONTROL("BACKUP-001"),
      CONTROL("VENDOR-001"),
      CONTROL("CLOUD-001"),
      CONTROL("EMG-001"),
    ],
    baselineScore: 86,
    baselineControls: { passed: 14, total: 16 },
  },
  {
    id: "dora",
    code: "DORA",
    name: "EU DORA Digital Operational Resilience Act",
    region: "DE",
    bloc: "EU",
    authority: "European Supervisory Authorities",
    status: "active",
    version: "EU 2022/2554",
    description: "EU regulation for digital operational resilience in the financial sector, including third-party ICT risk.",
    intent: "Ensure financial entities maintain operational resilience over ICT and manage ICT third-party risk.",
    whyApplies: "Applies because the organization operates in the EU financial sector or supplies ICT services to EU financial entities.",
    triggers: [
      { field: "regions", operator: "in", value: ["EU"] },
      { field: "industries", operator: "any", value: ["finance", "banking", "software-saas", "cloud-provider"] },
    ],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("ACCESS-001"),
      CONTROL("SEG-001"),
      CONTROL("PROTO-001"),
      CONTROL("MGMT-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("IR-001"),
      CONTROL("PATCH-001"),
      CONTROL("BACKUP-001"),
      CONTROL("VENDOR-001"),
      CONTROL("CLOUD-001"),
      CONTROL("AUDIT-001"),
      CONTROL("EMG-001"),
    ],
    baselineScore: 84,
    baselineControls: { passed: 12, total: 14 },
  },
  {
    id: "gdpr",
    code: "GDPR",
    name: "EU General Data Protection Regulation",
    region: "DE",
    bloc: "EU",
    authority: "European Commission / EDPB",
    status: "active",
    version: "EU 2016/679",
    description: "EU regulation governing the processing of personal data of individuals in the EU.",
    intent: "Protect EU data subjects' rights and ensure lawful, secure processing of personal data.",
    whyApplies: "GDPR applies because the organization processes personal data of individuals located in the EU.",
    triggers: [
      { field: "regions", operator: "in", value: ["EU"] },
      { field: "customerRegions", operator: "any", value: ["EU"] },
      { field: "dataTypes", operator: "any", value: ["PERSONAL"] },
    ],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("ACCESS-001"),
      CONTROL("PROTO-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("DATA-001"),
      CONTROL("IR-001"),
      CONTROL("AUDIT-001"),
    ],
    baselineScore: 94,
    baselineControls: { passed: 7, total: 8 },
  },
  {
    id: "certin",
    code: "CERT-In",
    name: "CERT-In Cybersecurity Directions",
    region: "IN",
    bloc: "INDIA",
    authority: "Indian Computer Emergency Response Team",
    status: "active",
    version: "2022",
    description: "Mandatory cyber security directions for service providers, intermediaries, data centres and government entities in India.",
    intent: "Meet CERT-In's mandatory security practices, log retention and incident reporting obligations.",
    whyApplies: "Applies because the organization operates in India and matches CERT-In-covered entity categories.",
    triggers: [{ field: "regions", operator: "in", value: ["IN"] }],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("AUTH-001"),
      CONTROL("ACCESS-001"),
      CONTROL("SEG-001"),
      CONTROL("DDENY-001"),
      CONTROL("PROTO-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("DATA-001"),
      CONTROL("IR-001"),
      CONTROL("ASSET-001"),
      CONTROL("PATCH-001"),
      CONTROL("BACKUP-001"),
      CONTROL("VENDOR-001"),
      CONTROL("CLOUD-001"),
      CONTROL("AUDIT-001"),
      CONTROL("EMG-001"),
    ],
    baselineScore: 92,
    baselineControls: { passed: 15, total: 17 },
  },
  {
    id: "dpdp",
    code: "DPDP",
    name: "India Digital Personal Data Protection Act",
    region: "IN",
    bloc: "INDIA",
    authority: "MeitY / DPDPB (gov.ind)",
    status: "draft",
    version: "2023",
    description: "Indian law governing processing of digital personal data, consent management and data fiduciary obligations.",
    intent: "Establish lawful bases, notice/consent management and reasonable safeguards for personal data in India.",
    whyApplies: "DPDP applies because the organization processes digital personal data of individuals in India.",
    triggers: [
      { field: "regions", operator: "in", value: ["IN"] },
      { field: "customerRegions", operator: "any", value: ["IN"] },
      { field: "dataTypes", operator: "any", value: ["PERSONAL"] },
    ],
    controlIds: [
      CONTROL("ACCESS-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("DATA-001"),
      CONTROL("IR-001"),
      CONTROL("AUDIT-001"),
    ],
    baselineScore: 88,
    baselineControls: { passed: 5, total: 6 },
  },
  {
    id: "nciplc",
    code: "NCIIPC Guidance",
    name: "NCIIPC Protection Guidance",
    region: "IN",
    bloc: "INDIA",
    authority: "National Critical Information Infrastructure Protection Centre",
    status: "under_review",
    version: "2023",
    description: "Guidance for the protection of National Critical Information Infrastructure (CII) in India.",
    intent: "Protect critical information infrastructure and controlled IT assets aligned to NCIIPC directives.",
    whyApplies: "Applies where the organization operates or services critical infrastructure designated as CII in India.",
    triggers: [
      { field: "regions", operator: "in", value: ["IN"] },
      { field: "industries", operator: "any", value: ["critical-infrastructure", "energy", "defense", "telecommunications", "finance", "banking", "government", "transportation"] },
    ],
    controlIds: [
      CONTROL("MFA-PRIV-001"),
      CONTROL("ACCESS-001"),
      CONTROL("SEG-001"),
      CONTROL("DDENY-001"),
      CONTROL("PROTO-001"),
      CONTROL("MGMT-001"),
      CONTROL("ADMIN-001"),
      CONTROL("LOG-001"),
      CONTROL("CRYPT-001"),
      CONTROL("IR-001"),
      CONTROL("ASSET-001"),
      CONTROL("PATCH-001"),
      CONTROL("BACKUP-001"),
      CONTROL("VENDOR-001"),
      CONTROL("AUDIT-001"),
    ],
    baselineScore: 85,
    baselineControls: { passed: 13, total: 15 },
  },
];

export const FRAMEWORK_INDEX = new Map<string, ComplianceFrameworkDef>(FRAMEWORKS.map((f) => [f.id, f]));

export const FRAMEWORK_META: Record<string, { label: string; color: string; text: string; chip: string }> = {
  GLOBAL: { label: "Global", color: "#38bdf8", text: "text-accent", chip: "border-accent/40 bg-accent/10 text-accent" },
  US: { label: "United States", color: "#7dd3fc", text: "text-sky-300", chip: "border-sky-500/40 bg-sky-500/10 text-sky-300" },
  EU: { label: "European Union", color: "#a78bfa", text: "text-violet-300", chip: "border-violet-500/40 bg-violet-500/10 text-violet-300" },
  INDIA: { label: "India", color: "#fbbf24", text: "text-amber-300", chip: "border-amber-500/40 bg-amber-500/10 text-amber-300" },
  APAC: { label: "APAC", color: "#5eead4", text: "text-teal-300", chip: "border-teal-500/40 bg-teal-500/10 text-teal-300" },
  OTHER: { label: "Other region", color: "#94a3b8", text: "text-slate-300", chip: "border-slate-500/40 bg-slate-500/10 text-slate-300" },
};

export function frameworkMeta(blocOrRegion: string): { label: string; color: string; text: string; chip: string } {
  return FRAMEWORK_META[blocOrRegion] ?? FRAMEWORK_META.OTHER;
}

export function frameworkDisplayCode(id: string): string {
  return FRAMEWORK_INDEX.get(id)?.code ?? id.toUpperCase();
}