import type { OrganizationProfile } from "@nexus/shared-types";

export const DEFAULT_ORG: OrganizationProfile = {
  id: "org-nexus-enterprise",
  name: "NEXUS Enterprise",
  regions: ["IN", "DE", "US"],
  industries: ["technology"],
  size: "ENTERPRISE",
  criticality: "HIGH",
  dataTypes: ["PERSONAL", "FINANCIAL", "CUSTOMER", "INTERNAL"],
  cloud: "MULTI_CLOUD",
  cloudProviders: ["AWS", "Azure", "GCP"],
  customerRegions: ["IN", "DE", "US", "SG"],
  businessSectors: ["TECH", "GOVERNMENT", "DEFENSE"],
  dataResidency: ["IN", "EU", "US"],
  description: "Global technology company operating across India, the EU and the United States with multi-cloud delivery.",
};

export const SEED_ORG_PROFILES: OrganizationProfile[] = [
  { ...DEFAULT_ORG },
  {
    id: "org-alt-lifesciences",
    name: "Altus Lifesciences",
    regions: ["US", "DE"],
    industries: ["healthcare"],
    size: "MID",
    criticality: "HIGH",
    dataTypes: ["HEALTH", "PERSONAL", "CUSTOMER", "INTERNAL"],
    cloud: "HYBRID",
    cloudProviders: ["AWS"],
    customerRegions: ["US", "EU"],
    businessSectors: ["HEALTH"],
    dataResidency: ["US", "EU"],
    description: "Healthcare organization processing protected health information across US and EU regions.",
  },
  {
    id: "org-novi-networks",
    name: "Novi Networks",
    regions: ["IN", "DE"],
    industries: ["telecommunications"],
    size: "ENTERPRISE",
    criticality: "CRITICAL",
    dataTypes: ["PERSONAL", "TELEMETRY", "INTERNAL"],
    cloud: "HYBRID",
    cloudProviders: ["Azure"],
    customerRegions: ["IN", "EU"],
    businessSectors: ["TELECOM"],
    dataResidency: ["IN", "EU"],
    description: "Telecommunications provider operating core network functions across India and the EU.",
  },
  {
    id: "org-ferro-industrial",
    name: "FerroWorks Manufacturing",
    regions: ["IN"],
    industries: ["manufacturing"],
    size: "MID",
    criticality: "MEDIUM",
    dataTypes: ["INTERNAL", "TELEMETRY"],
    cloud: "EDGE",
    cloudProviders: ["Azure"],
    customerRegions: ["IN", "US"],
    businessSectors: ["MANUFACTURING"],
    dataResidency: ["IN"],
    description: "Manufacturing organization operating industrial control systems with a legacy OT estate.",
  },
  {
    id: "org-skyward-cloud",
    name: "Skyward Cloud",
    regions: ["US", "DE", "SG"],
    industries: ["cloud-provider", "software-saas"],
    size: "ENTERPRISE",
    criticality: "HIGH",
    dataTypes: ["PERSONAL", "CUSTOMER", "SOURCECODE", "INTERNAL"],
    cloud: "CLOUD",
    cloudProviders: ["AWS", "GCP"],
    customerRegions: ["US", "EU", "APAC"],
    businessSectors: ["CLOUD", "PUBLIC_SECTOR"],
    dataResidency: ["US", "EU"],
    description: "Cloud/SaaS provider delivering multi-tenant identity and platform services globally.",
  },
  {
    id: "org-federal-grid",
    name: "Federal Grid Authority",
    regions: ["IN", "US"],
    industries: ["government", "critical-infrastructure"],
    size: "GOVERNMENT",
    criticality: "CRITICAL",
    dataTypes: ["CLASSIFIED", "INTERNAL", "TELEMETRY"],
    cloud: "ON_PREM",
    cloudProviders: [],
    customerRegions: ["IN", "US"],
    businessSectors: ["GOVERNMENT", "CRITICAL_INFRA"],
    dataResidency: ["IN", "US"],
    description: "Government critical-infrastructure operator requiring highest-assurance security hardening.",
  },
];

export function orgProfileById(id: string): OrganizationProfile | undefined {
  return SEED_ORG_PROFILES.find((o) => o.id === id);
}