import { Bot, CheckCircle2, ClipboardCheck, Edit3, FileSearch, Flag, Lock, RefreshCw, ShieldCheck, ThumbsDown, Undo2, XCircle, type LucideIcon } from "lucide-react";
import type { AuditEventRecord } from "../types";
import { cn, formatDate, timeAgo } from "../utils/cn";

const LABELS: Record<string, string> = {
  FINDING_AI_GENERATED: "Finding generated by the analysis engine / AI",
  FINDING_ENTERED_REVIEW: "Entered the Human Review Queue",
  FINDING_APPROVED: "Approved by human reviewer",
  FINDING_REJECTED: "Rejected by human reviewer",
  FINDING_CHANGES_REQUESTED: "Changes requested",
  FINDING_MODIFIED: "Recommendation modified by human reviewer",
  FINDING_REOPENED: "Reopened for review",
  FINDING_RESOLVED: "Resolved in the finalized assessment",
  AUDIT_FINALIZED: "Compliance assessment finalized — sealed",
  AI_INTERPRETATION_APPROVED: "AI interpretation approved",
  AI_INTERPRETATION_REJECTED: "AI interpretation rejected",
  AI_INTERPRETATION_EDITED: "AI interpretation edited",
};

const ICONS: Record<string, LucideIcon> = {
  FINDING_AI_GENERATED: Bot,
  FINDING_ENTERED_REVIEW: ClipboardCheck,
  FINDING_APPROVED: CheckCircle2,
  FINDING_REJECTED: XCircle,
  FINDING_CHANGES_REQUESTED: Flag,
  FINDING_MODIFIED: Edit3,
  FINDING_REOPENED: Undo2,
  FINDING_RESOLVED: ShieldCheck,
  AUDIT_FINALIZED: Lock,
  AI_INTERPRETATION_APPROVED: FileSearch,
  AI_INTERPRETATION_REJECTED: ThumbsDown,
  AI_INTERPRETATION_EDITED: RefreshCw,
};

const SOURCE_STYLES: Record<string, string> = {
  system: "text-slate-400 border-slate-500/40 bg-slate-500/10",
  ai: "text-cyan-300 border-cyan-500/40 bg-cyan-500/10",
  human: "text-emerald-300 border-emerald-500/40 bg-status-ok-soft",
};

function detailSummary(e: AuditEventRecord): string {
  const replay: Record<string, string> = {
    previousStatus: "Previous status",
    newStatus: "Status",
    rejectionReason: "Rejection reason",
    requestedChanges: "Requested change",
    comment: "Comment",
    reason: "Reason",
    note: "Note",
  };
  const d = e.detail ?? {};
  const parts: string[] = [];
  for (const [k, v] of Object.entries(d)) {
    if (v == null || v === "") continue;
    if (k === "originalAiRecommendation" || k === "humanModifiedRecommendation" || k === "approvedRecommendation") {
      const rec = v as { recommendedFix?: string; why?: string };
      parts.push(`${replay[k] ?? k}: ${String(rec?.recommendedFix ?? rec?.why ?? JSON.stringify(v))}`);
      continue;
    }
    parts.push(`${replay[k] ?? k}: ${String(v)}`);
  }
  return parts.join(" · ");
}

export function AuditTrailTimeline({ items }: { items: AuditEventRecord[] }) {
  if (!items.length) {
    return <p className="text-sm text-slate-500">No audit events recorded yet.</p>;
  }
  return (
    <ol className="audit-line relative border-l border-surface-700 ml-3 space-y-5">
      {[...items].reverse().map((e, idx) => {
        const Icon = ICONS[e.eventType] ?? FileSearch;
        const humanAction = e.source === "human";
        const sealNode = e.eventType === "AUDIT_FINALIZED";
        return (
          <li key={e.id} className="pl-6 relative row-in" style={{ animationDelay: `${idx * 70}ms`, ["--node-delay" as never]: `${idx * 90}ms` }}>
            <span
              className={cn(
                "timeline-node absolute -left-[9px] top-0.5 w-[17px] h-[17px] rounded-full border flex items-center justify-center",
                sealNode
                  ? "border-teal-400/70 bg-teal-500/15"
                  : humanAction
                    ? "border-emerald-500/50 bg-emerald-500/10"
                    : "border-surface-600 bg-surface-900"
              )}
            >
              <Icon className={cn("timeline-icon w-2.5 h-2.5", sealNode ? "text-teal-300" : humanAction ? "text-emerald-300" : "text-accent")} aria-hidden="true" />
            </span>
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-sm font-medium text-slate-200">{LABELS[e.eventType] ?? e.eventType.replaceAll("_", " ")}</span>
              <span className={cn("chip border text-[9px] font-bold uppercase", SOURCE_STYLES[e.source] ?? SOURCE_STYLES.system)}>{e.source}</span>
            </div>
            <div className="text-[11px] text-slate-500 mt-0.5" title={formatDate(e.at)}>
              {e.actorName ?? "System"} · {e.actorRole ?? ""} · {timeAgo(e.at)}
            </div>
            {detailSummary(e) ? <p className="text-xs text-slate-400 mt-1 leading-relaxed">{detailSummary(e)}</p> : null}
          </li>
        );
      })}
    </ol>
  );
}