import type {
  ComplianceControl,
  Severity,
} from "@nexus/shared-types";

const PROTOTYPE_NOTICE =
  "Prototype Control. Inspired by CIS/NIST/STIG security principles. Not an official control identifier.";

export const CONTROLS: ComplianceControl[] = [
  {
    id: "NET-SSH-001",
    name: "Restrict SSH Administrative Access",
    description: "SSH management access must be restricted to approved administrative networks.",
    frameworks: ["CIS", "NIST", "PROTOTYPE"],
    severity: "HIGH",
    condition: { intentType: "RESTRICT_ADMIN_ACCESS", sourceRestriction: true },
    failureMessage: "Administrative SSH access is not restricted to approved networks.",
    remediation: "Restrict SSH access to trusted administrative networks (e.g. 10.0.0.0/24).",
    prototypeLabel: false,
  },
  {
    id: "NET-TELNET-001",
    name: "Telnet Disabled",
    description: "Insecure Telnet must not be enabled for device access.",
    frameworks: ["CIS", "NIST", "PROTOTYPE"],
    severity: "CRITICAL",
    condition: { intentType: "DISABLE_INSECURE_PROTOCOL", protocol: "telnet", disabled: true },
    failureMessage: "Telnet is enabled providing unencrypted administrative access.",
    remediation: "Disable Telnet and use SSH for all device management.",
    prototypeLabel: false,
  },
  {
    id: "NET-MGMT-002",
    name: "Management Access Restriction",
    description: "Management interfaces must not be exposed to the internet or unrestricted networks.",
    frameworks: ["CIS", "NIST", "PROTOTYPE"],
    severity: "HIGH",
    condition: {
      intentType: "SECURE_MANAGEMENT_INTERFACE",
      restricted: true,
      internetExposed: false,
    },
    failureMessage: "Management interface is exposed beyond approved administrative networks.",
    remediation: "Bind management interfaces to private networks and restrict source addresses.",
    prototypeLabel: false,
  },
  {
    id: "NET-LOG-003",
    name: "Logging Enabled",
    description: "Security-relevant events must be logged.",
    frameworks: ["CIS", "NIST", "STIG", "PROTOTYPE"],
    severity: "MEDIUM",
    condition: { intentType: "REQUIRE_LOGGING", loggingEnabled: true },
    failureMessage: "Required logging is not enabled for this security-relevant feature.",
    remediation: "Enable logging for administrative access and security events.",
    prototypeLabel: false,
  },
  {
    id: "NET-SRC-004",
    name: "Source Network Restriction",
    description: "Traffic sources must be restricted to approved networks.",
    frameworks: ["CIS", "NIST", "PROTOTYPE"],
    severity: "MEDIUM",
    condition: { intentType: "RESTRICT_SOURCE_NETWORK", sourceRestriction: true },
    failureMessage: "Traffic is allowed from an unrestricted source (e.g. any/0.0.0.0/0).",
    remediation: "Restrict permitted source networks to approved ranges.",
    prototypeLabel: false,
  },
  {
    id: "NET-INSEC-005",
    name: "Insecure Protocol Detection",
    description: "Insecure protocols must be disabled where secure alternatives exist.",
    frameworks: ["CIS", "PROTOTYPE"],
    severity: "HIGH",
    condition: { intentType: "DISABLE_INSECURE_PROTOCOL", insecure: true },
    failureMessage: "An insecure protocol is enabled on this device.",
    remediation: "Replace insecure protocols with encrypted equivalents.",
    prototypeLabel: true,
  },
  {
    id: "NET-DDENY-006",
    name: "Default Deny",
    description: "Traffic should be denied by default unless explicitly permitted.",
    frameworks: ["CIS", "NIST", "PROTOTYPE"],
    severity: "HIGH",
    condition: { intentType: "DEFAULT_DENY", defaultDeny: true },
    failureMessage: "No default-deny policy is in place; unspecified traffic may be permitted.",
    remediation: "Apply a default-deny policy and explicitly permit only required traffic.",
    prototypeLabel: false,
  },
  {
    id: "NET-AUTH-007",
    name: "Require Strong Authentication",
    description: "Device access must require strong (non-plaintext) authentication.",
    frameworks: ["CIS", "NIST", "STIG", "PROTOTYPE"],
    severity: "HIGH",
    condition: { intentType: "REQUIRE_STRONG_AUTHENTICATION", strongAuth: true },
    failureMessage: "Weak or absent authentication is used for device access.",
    remediation: "Enforce strong, encrypted authentication for all device access.",
    prototypeLabel: false,
  },
  {
    id: "NET-ADMEX-008",
    name: "Administrative Exposure",
    description: "Administrative services must not be reachable from the internet.",
    frameworks: ["CIS", "NIST", "PROTOTYPE"],
    severity: "CRITICAL",
    condition: { intentType: "RESTRICT_ADMIN_ACCESS", internetExposed: false },
    failureMessage: "Administrative services are exposed to an untrusted (internet) source.",
    remediation: "Place management services behind the firewall on a private network.",
    prototypeLabel: false,
  },
  {
    id: "NET-DENY-009",
    name: "Deny Unauthorized Traffic",
    description: "Unauthorized or default-permit traffic must be explicitly denied.",
    frameworks: ["CIS", "PROTOTYPE"],
    severity: "MEDIUM",
    condition: { intentType: "DENY_UNAUTHORIZED_TRAFFIC", denied: true },
    failureMessage: "Configuration explicitly permits traffic without an accompanying deny policy.",
    remediation: "Add explicit deny rules for unauthorized traffic.",
    prototypeLabel: true,
  },
  {
    id: "NET-SEG-010",
    name: "Network Segmentation",
    description: "Security zones must be segmented to limit lateral movement.",
    frameworks: ["CIS", "NIST", "PROTOTYPE"],
    severity: "MEDIUM",
    condition: { intentType: "NETWORK_SEGMENTATION", segmented: true },
    failureMessage: "No segmentation between security zones is evident.",
    remediation: "Segment networks into zones and enforce allow-only between them.",
    prototypeLabel: false,
  },
  {
    id: "NET-SVC-011",
    name: "Unnecessary Services Disabled",
    description: "Unnecessary network services must be disabled to reduce attack surface.",
    frameworks: ["CIS", "NIST", "PROTOTYPE"],
    severity: "LOW",
    condition: { intentType: "DEFAULT_DENY", unnecessaryServicesDisabled: true },
    failureMessage: "Unnecessary services are enabled on the device.",
    remediation: "Disable non-essential services on the device.",
    prototypeLabel: true,
  },
  {
    id: "NET-HTTPS-012",
    name: "Secure Management Web Interface",
    description: "Web management interface must use HTTPS, not plain HTTP.",
    frameworks: ["CIS", "PROTOTYPE"],
    severity: "MEDIUM",
    condition: { intentType: "SECURE_MANAGEMENT_INTERFACE", https: true },
    failureMessage: "Web management interface uses insecure HTTP.",
    remediation: "Enable HTTPS for the management web interface.",
    prototypeLabel: false,
  },
  {
    id: "NET-SNMP-013",
    name: "SNMP Community Restriction",
    description: "SNMP must not be enabled with default or public community strings.",
    frameworks: ["CIS", "NIST", "PROTOTYPE"],
    severity: "MEDIUM",
    condition: { intentType: "DISABLE_INSECURE_PROTOCOL", protocol: "snmp", communityRestricted: true },
    failureMessage: "SNMP is enabled with a weak or public community string.",
    remediation: "Disable SNMP or restrict it using strong community strings and source ACLs.",
    prototypeLabel: true,
  },
  {
    id: "NET-TFNTP-014",
    name: "TFTP Disabled",
    description: "Insecure TFTP should not be enabled.",
    frameworks: ["CIS", "PROTOTYPE"],
    severity: "LOW",
    condition: { intentType: "DISABLE_INSECURE_PROTOCOL", protocol: "tftp", disabled: true },
    failureMessage: "TFTP is enabled on the device.",
    remediation: "Disable TFTP.",
    prototypeLabel: true,
  },
  {
    id: "NET-SNMPRO-015",
    name: "SNMP Traps Secure",
    description: "SNMP traps should use SNMPv3 or be restricted.",
    frameworks: ["CIS", "PROTOTYPE"],
    severity: "LOW",
    condition: { intentType: "DISABLE_INSECURE_PROTOCOL", protocol: "snmp", trapsSecure: true },
    failureMessage: "SNMP traps are configured insecurely.",
    remediation: "Use SNMPv3 or restrict trap destinations.",
    prototypeLabel: true,
  },
];

export function getControls(): ComplianceControl[] {
  return CONTROLS;
}

export function getControlById(id: string): ComplianceControl | undefined {
  return CONTROLS.find((c) => c.id === id);
}

export const SEVERITY_WEIGHT: Record<Severity, number> = {
  CRITICAL: 1.0,
  HIGH: 0.75,
  MEDIUM: 0.5,
  LOW: 0.25,
  INFO: 0.1,
};

export { PROTOTYPE_NOTICE };
