import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Cpu, Lock, Database, Activity, LogOut } from "lucide-react";
import { PageHeader } from "../components/PageHeader";
import { Logo } from "../components/Logo";
import { useAiMode } from "../hooks/useAiMode";
import { currentUser, signOut } from "../session";
import { api } from "../services/api";

export default function SettingsPage() {
  const { mode, checked } = useAiMode();
  const user = currentUser();
  const [health, setHealth] = useState<{ ok: boolean; latency?: number } | null>(null);
  const [db, setDb] = useState<{ audits: number; approxBytes?: number } | null>(null);

  useEffect(() => {
    const t0 = performance.now();
    const done = (ok: boolean) => setHealth({ ok, latency: Math.round(performance.now() - t0) });
    fetch(`${import.meta.env.VITE_API_URL ?? "/api"}/health`).then((r) => done(r.ok)).catch(() => done(false));
    api
      .listAudits()
      .then((a) => setDb({ audits: a.length, approxBytes: JSON.stringify(a).length }))
      .catch(() => setDb(null));
  }, []);

  return (
    <div className="max-w-3xl">
      <PageHeader title="Settings" subtitle="Workspace, intelligence provider, and storage information for this prototype." />

      <div className="space-y-4">
        <div className="card !p-5 row-in">
          <h2 className="text-base font-semibold text-slate-100 mb-1">Profile</h2>
          <p className="text-xs text-slate-500 mb-4">The demo workspace signs you in as a Security Analyst (view-role).</p>
          <div className="flex items-center gap-3">
            <span className="w-11 h-11 rounded-full bg-gradient-to-br from-accent to-accent-dim text-slate-950 flex items-center justify-center text-sm font-bold">
              {user.split(" ").map((w) => w[0]).slice(0, 2).join("").toUpperCase()}
            </span>
            <div className="flex-1">
              <div className="text-sm font-semibold text-slate-100">{user}</div>
              <div className="text-xs text-slate-500">Security Analyst · Workspace: SIH-2026-DEMO</div>
            </div>
            <button className="btn-outline !px-3 !py-2 text-xs" onClick={() => signOut()}>
              <LogOut className="w-3.5 h-3.5" aria-hidden="true" /> Sign out
            </button>
          </div>
        </div>

        <div className="card !p-5 row-in" style={{ animationDelay: "80ms" }}>
          <h2 className="text-base font-semibold text-slate-100 mb-4">Intelligence provider</h2>
          <div className="flex items-start gap-3 rounded-lg border border-surface-700 bg-surface-850 p-3.5">
            <Activity className="w-5 h-5 text-accent mt-0.5" aria-hidden="true" />
            <div className="flex-1">
              <div className="text-sm font-medium text-slate-200 flex items-center gap-2">
                {mode === "live" ? "Live AI engine" : "Offline deterministic engine"}
                <span className={`chip border ${mode === "live" ? "border-emerald-500/40 bg-status-ok-soft text-emerald-300" : "border-amber-500/40 bg-status-warn-soft text-amber-300"}`}>
                  {checked ? (mode === "live" ? "LIVE" : "DEMO") : "checking…"}
                </span>
              </div>
              <p className="text-xs text-slate-500 mt-1 leading-relaxed">
                {mode === "live"
                  ? "Interpretations are generated by the configured AI endpoint."
                  : "No external AI endpoint is running — vendor detection and interpretations fall back to the transparent deterministic interpreter so the demo works fully offline."}
              </p>
            </div>
          </div>
        </div>

        <div className="card !p-5 row-in" style={{ animationDelay: "160ms" }}>
          <h2 className="text-base font-semibold text-slate-100 mb-4">Data & storage</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="rounded-lg border border-surface-700 bg-surface-850 p-3.5 flex items-center gap-3">
              <Database className="w-5 h-5 text-accent" aria-hidden="true" />
              <div>
                <div className="text-sm text-slate-200">{db ? `${db.audits} audits stored` : "checking…"}</div>
                <div className="text-[11px] text-slate-500 mt-0.5">JSON persistence · data/db.json</div>
              </div>
            </div>
            <div className="rounded-lg border border-surface-700 bg-surface-850 p-3.5 flex items-center gap-3">
              <Cpu className="w-5 h-5 text-accent" aria-hidden="true" />
              <div>
                <div className="text-sm text-slate-200">{health ? (health.ok ? "Engine online" : "Engine offline") : "checking…"}</div>
                <div className="text-[11px] text-slate-500 mt-0.5">{health?.latency ? `health probe ${health.latency}ms` : "health endpoint"}</div>
              </div>
            </div>
          </div>
          <p className="mt-4 text-[11px] text-slate-600 leading-relaxed">
            To reset the demonstration dataset: stop the stack, delete <code className="text-slate-400">data/db.json</code>, then run <code className="text-slate-400">npm run demo</code> to bring up a pristine seeded workspace.
          </p>
        </div>

        <div className="card !p-5">
          <h2 className="text-base font-semibold text-slate-100 mb-3">Security posture</h2>
          <ul className="space-y-2.5 text-xs text-slate-400">
            <li className="flex items-center gap-2.5"><Lock className="w-3.5 h-3.5 text-accent" aria-hidden="true" /> Secrets (passwords, keys) redacted before any external analysis call.</li>
            <li className="flex items-center gap-2.5"><Lock className="w-3.5 h-3.5 text-accent" aria-hidden="true" /> Interpretations stored PENDING until explicitly approved by a human.</li>
            <li className="flex items-center gap-2.5"><Lock className="w-3.5 h-3.5 text-accent" aria-hidden="true" /> Remediation is safety-simulated — the original configuration is never mutated.</li>
            <li className="flex items-center gap-2.5"><Lock className="w-3.5 h-3.5 text-accent" aria-hidden="true" /> Every finding carries line-level evidence and a full decision trail.</li>
          </ul>
        </div>

        <div className="flex items-center justify-between pt-2">
          <Link to="/" className="text-xs text-slate-500 hover:text-slate-300">Product overview</Link>
          <Logo size={26} />
        </div>
      </div>
    </div>
  );
}